steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE=gcr.io/$PROJECT_ID/zag:v0.15.2.1'
      - '--tag'
      - '1z-build:local'
      - '.'

  - name: 'bash'
    args:
      - -c
      - |
        chown -R 65532:999 /workspace

  - name: '1z-build:local'
    env:
      - ZIG_GLOBAL_CACHE_DIR=/home/build/.cache/zig
      - ZIG_LOCAL_CACHE_DIR=/home/build/.zig-cache
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eux
        mkdir -p /home/build/.cache/zig
        mkdir -p /home/build/.zig-cache
        make build
        make TIMEOUT=300 test
        make run ARGS=./examples/showcase.1z
