steps:
  - name: 'bash'
    args:
      - -c
      - |
        chown -R 65532:999 /workspace

  - name: 'gcr.io/$PROJECT_ID/zag:v0.15.2.1'
    env:
      - ZIG_GLOBAL_CACHE_DIR=/home/build/.cache/zig
      - ZIG_LOCAL_CACHE_DIR=/home/build/.zig-cache
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -eux
        mkdir -p /home/build/.cache/zig
        mkdir -p /home/build/.zig-cache
        make build
        make TIMEOUT=60 test
        ./zig-out/bin/1z ./examples/showcase.1z
